using DesignProjectStructure.Models;

namespace DesignProjectStructure.FileTypes;

/// <summary>
/// HTML output generator with a modern design
/// </summary>
public class OutputHtmlGenerator : IOutputGenerator
{
    public string Generate(StructureItens structureItens, string rootPath)
    {
        // Convert the complete structure (which has Unicode icons) to HTML
        var htmlStructure = structureItens.CompleteStructure.ToString()
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");

        // Remove the header lines (Project Structure:, Path:, Generated in:, ====)
        var lines = htmlStructure.Split('\n');
        var structureLines = lines.Skip(4).Where(line => !string.IsNullOrWhiteSpace(line));
        var cleanStructure = string.Join("\n", structureLines);

        var html = GenerateHtmlTemplate(structureItens, rootPath, cleanStructure);
        return html;
    }

    public string GetFileExtension() => "html";

    public string GetFormatName() => "HTML";

    public bool SupportsFormat(string format) =>
        format.Equals("html", StringComparison.OrdinalIgnoreCase) ||
        format.Equals("htm", StringComparison.OrdinalIgnoreCase);

    #region Template HTML

    private string GenerateHtmlTemplate(StructureItens structureItens, string rootPath, string cleanStructure)
    {
        return $@"<!DOCTYPE html>
<html lang=""pt-BR"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>Project Structure - {Path.GetFileName(rootPath)}</title>
    <style>
        {GetCssStyles()}
    </style>
</head>
<body>
    <div class=""container"">
        <header class=""header"">
            <h1>📁 Project Structure</h1>
            <div class=""subtitle"">🎯 {Path.GetFileName(rootPath)}</div>
            <div class=""subtitle"">📍 {rootPath}</div>
            <div class=""subtitle"">🕒 Generated on {DateTime.Now:dd/MM/yyyy HH:mm:ss}</div>
        </header>
        
        <section class=""stats"">
            <div class=""stat-item"">
                <span class=""stat-number"">{structureItens.FolderCounter}</span>
                <span class=""stat-label"">📁 Folders</span>
            </div>
            <div class=""stat-item"">
                <span class=""stat-number"">{structureItens.FileCounter}</span>
                <span class=""stat-label"">📄 Files</span>
            </div>
            <div class=""stat-item"">
                <span class=""stat-number"">{structureItens.ProcessedItems}</span>
                <span class=""stat-label"">✅ Total Items</span>
            </div>
        </section>
        
        <section class=""structure"">
            <h2>🌳 File Tree Structure</h2>
            <div class=""tree""><pre>{cleanStructure}</pre></div>
        </section>
        
        <footer class=""footer"">
            <p>🚀 Generated by <strong>Design Project Structure</strong> | 
               ⚡ Processing completed in milliseconds | 
               💻 <a href=""https://github.com/yourusername/design-project-structure"" target=""_blank"">View on GitHub</a>
            </p>
        </footer>
    </div>
</body>
</html>";
    }

    private string GetCssStyles()
    {
        return @"
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 15px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }
        
        .header .subtitle {
            font-size: 1.1em;
            opacity: 0.9;
            margin: 5px 0;
        }
        
        .stats {
            background: #ecf0f1;
            padding: 20px 30px;
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
            border-bottom: 1px solid #bdc3c7;
        }
        
        .stat-item {
            text-align: center;
            margin: 10px;
        }
        
        .stat-number {
            font-size: 2em;
            font-weight: bold;
            color: #2c3e50;
            display: block;
        }
        
        .stat-label {
            color: #7f8c8d;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .structure {
            padding: 30px;
            background: #fafafa;
        }
        
        .structure h2 {
            color: #2c3e50;
            margin-bottom: 20px;
            font-size: 1.5em;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        
        .tree {
            background: #2c3e50;
            color: #ecf0f1;
            padding: 25px;
            border-radius: 10px;
            font-family: 'Courier New', 'Monaco', 'Menlo', monospace;
            font-size: 14px;
            line-height: 1.6;
            overflow-x: auto;
            box-shadow: inset 0 2px 10px rgba(0,0,0,0.1);
        }
        
        .footer {
            background: #34495e;
            color: white;
            padding: 20px;
            text-align: center;
            font-size: 0.9em;
        }
        
        .footer a {
            color: #3498db;
            text-decoration: none;
        }
        
        .footer a:hover {
            text-decoration: underline;
        }
        
        @media (max-width: 768px) {
            body { padding: 10px; }
            .header { padding: 20px; }
            .header h1 { font-size: 2em; }
            .stats { padding: 15px; }
            .structure { padding: 20px; }
            .tree { padding: 15px; font-size: 12px; }
        }";
    }

    #endregion
}